kilogram/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from kilogram import views

app_name = 'kilogram'

urlpatterns = [


    url(r'^$',login_required(views.IndexView.as_view()), name = 'index'),
    url(r'^upload$', views.upload, name = 'upload'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from kilogram import views as kilogram_views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', login_required(kilogram_views.IndexView.as_view()), name='root'),
    url(r'^kilogram/', include('kilogram.urls')),

    #Account-related views.
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/signup$', kilogram_views.CreateUserView.as_view(), name='signup'),
    url(r'^accounts/signup/done$', kilogram_views.RegistrationCompletedView.as_view(), name='created_user'),

    url('', include('social_django.urls', namespace='social')),

]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

kilogram/models.py
from django.conf import settings
from django.db import models

# Create your models here.

def user_path(instance, filename):
    from random import choice
    import string

    arr = [choice(string.ascii_letters) for _ in range(8)]
    pid = ''.join(arr)
    ext = filename.split('.')[-1]
    return '%s/%s.%s' % (instance.owner.username, pid, ext)


class Photo(models.Model):
    image = models.ImageField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    thumbnail_image = models.ImageField(blank=True)
    comment = models.CharField(max_length=255)
    pub_date = models.DateTimeField(auto_now_add=True)


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=64, default='hello')
    profile_picture = models.ImageField(blank=True)

kilogram/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User

from kilogram.models import Photo


class CreateUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(CreateUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        if commit:
            user.save()
        return user


class UploadForm(forms.ModelForm):
    comment = forms.CharField(max_length=255)

    class Meta:
        model = Photo
        exclude = ('thumbnail_image', 'owner')

kilogram/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.base import TemplateView
# Create your views here.
from kilogram.forms import CreateUserForm, UploadForm


@login_required
def upload(request):
    if request.method == "POST":
        form = UploadForm(request.POST, request.FILES)

        if form.is_valid():
            photo = form.save(commit=False)
            photo.owner = request.user
            form.save()
            return redirect('kilogram:index')


    form = UploadForm()
    return render(request, 'kilogram/upload.html', {'form' : form})



class IndexView(ListView):
    # model = Photo

    context_object_name = 'user_photo_list'
    paginate_by = 1

    def get_queryset(self):
        user = self.request.user
        return user.photo_set.all().order_by('-pub_date')

class CreateUserView(CreateView):
    template_name = 'registration/signup.html'

    form_class = CreateUserForm
    success_url = reverse_lazy('created_user')

class RegistrationCompletedView(TemplateView):
    template_name = 'registration/signup_done.html'

kilogram/templates/kilogram/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>Kilogram</title>

  <!-- Bootstrap -->
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">

  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static 'kilogram/style.css' %}" />

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body>
  <nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'kilogram:index' %}"> <span class="glyphicon glyphicon-camera"> </span> Kilogram </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
          {% if user.is_active %}
              <li><a href="#"> <span class="glyphicon glyphicon-heart"></span> {{ user.username }} </a> </li>
              <li><a href="{% url 'logout' %}">Logout</a></li>
              {% else %}
              <li><a href="{% url 'login' %}"> <span class="glyphicon glyphicon-user"></span> Login</a></li>
              <li><a href="{% url 'admin:index' %}">Admin</a></li>
          {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  <div class="container">
    <div>
      {% block content %}
      {% endblock %}
    </div>
  </div>
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

kilogram/templates/kilogram/index.html
{% extends 'kilogram/base.html' %}
{% block content %}

<h1>Kilogram Main Page</h1>

{% endblock %}

kilogram/templates/kilogram/photo_list.html
{% extends 'kilogram/base.html' %}
{% block content %}

<p> <a class="btn btn-primary" href="{% url 'kilogram:upload'%}">업로드</a></p>

  {% if user_photo_list %}
  {% for photo in user_photo_list %}
  <div class="panel panel-default" align="center">
    <div class="panel-heading"><h4>{{photo.owner.username}}</h4></div>
    <div class="panel-body">
      {% if photo.image.width > 800 %}
      <p><img src = '{{photo.image.url}}' width='600' /> <br>
        {% else %}
        <p><img src = '{{photo.image.url}}' /> <br>
          {% endif %}
          {{photo.comment}}</p>
      </div>
    </div>
      {% endfor %}
      {% else %}
      <h4>아직 사진이 없네요. 첫번째 사진을 업로드하세요!</h4>
      {% endif %}

    <!-- pagenation nav -->
    {% if is_paginated %}
    <nav aria-label="...">
        <ul class="pager">
          {% if page_obj.has_previous %}
          <li><a href="{%url 'kilogram:index'%}?page={{ page_obj.previous_page_number }}">이전</a></li>
          {% endif %}
          <li> <a href="#">페이지 {{ page_obj.number }} / {{ page_obj.paginator.num_pages }} </a></li>
          {% if page_obj.has_next %}
          <li>
            <a href="{%url 'kilogram:index'%}?page={{ page_obj.next_page_number }}">다음</a>
          </li>
          {% endif %}
        </ul>
    </nav>
    {% endif %}

{% endblock %}

kilogram/templates/kilogram/upload.html
{% extends 'kilogram/base.html' %}
{% block content %}

<h1>Kilogram Image Upload</h1>

<form action="{% url 'kilogram:upload' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Upload" />
</form>
{% endblock %}